group=com.caelcs
name=quarkus-template
version=1.0.0

quarkusPluginId=io.quarkus
quarkusPluginVersion=3.29.3
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.29.3

lombokVersion=1.18.42
archunitVersion=1.4.1
mockitoVersion=5.20.0
mapStructVersion=1.6.3
quarkusWiremockVersion=1.5.1
spotBugsVersion=4.9.8
