quarkus:

  log:
    console:
      json:
        enabled: true
    level: ERROR
    category:
      "org.hibernate":
        level: WARN

  datasource:
    db-kind: postgresql
    username: template
    password: IAmMasterChief
    jdbc:
      url: jdbc:postgresql://postgres-template-pg:5432/hibernate_orm_test
      max-size: 16