quarkus:

  oidc:
    auth-server-url: ${keycloak.url}/realms/${keycloak.default.realm}
    client-id: ${keycloak.default.client-id}
    credentials:
      secret: ${keycloak.default.client-secret}

  log:
    console:
      json:
        enabled: false
    level: INFO
    category:
      "org.hibernate":
        level: INFO

  datasource:
    db-kind: h2
    username: username-default
    jdbc:
      url: jdbc:h2:mem:testdb
      max-size: 13

  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.xml

app:
  rest-client:
    transactions-api:
      url: http://localhost:8090
      connection-pool-size: 20
      max-connections: 50
      connection-ttl: 60
      connection-timeout: 10
      idle-timeout: 30

