quarkus:

  log:
    console:
      json:
        enabled: true
    level: ERROR
    category:
      "org.hibernate":
        level: WARN

  datasource:
    db-kind: postgresql
    jdbc:
      max-size: 50
      min-size: 10
      initial-size: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000

  thread-pool:
    core-threads: 10
    max-threads: 50
    queue-size: 100

  vertx:
    event-loops-pool-size: 32
    worker-pool-size: 50
    internal-blocking-pool-size: 50