services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkusdb
    ports:
      - "5432:5432"
    networks:
      - quarkus-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  quarkus-app:
    image: adolfoecs/quarkus-template:latest
    container_name: quarkus_app
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkusdb
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
    ports:
      - "8080:8080"
    networks:
      - quarkus-net

networks:
  quarkus-net:
    driver: bridge

volumes:
  postgres-data: