apiVersion: batch/v1
kind: Job
metadata:
  name: gatling-test
spec:
  template:
    metadata:
      labels:
        app: gatling
    spec:
      containers:
        - name: gatling
          image: adolfoecs/quarkus-template-gatling:1.0.1
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak:8080"
            - name: QUARKUS_APP_URL
              value: "http://quarkus-app:8080"
            - name: CONCURRENT_USERS
              value: "100"
            - name: DURATION
              value: "1000"
      restartPolicy: Never
