---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods","endpoints","services"]
    verbs: ["get", "list","watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["podmonitors"]
    verbs: ["get", "list", "create", "delete","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default  # Adjust this if your Prometheus is in a different namespace
roleRef:
  kind: ClusterRole
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: quarkus-app
  namespace: default
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: quarkus-app  # Label your app's pods accordingly
  podMetricsEndpoints:
    - port: web  # Ensure this matches the port name in your Quarkus app's deployment
      path: /q/metrics  # The path where metrics are exposed
      interval: 5s
      targetPort: 8080
---
# 4️⃣ Prometheus Deployment
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 1
  serviceAccountName: prometheus
  version: v2.55.1
  podMonitorSelector:
    matchLabels:
      team: backend
  resources:
    requests:
      memory: 400Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1
  retention: 15d
---
# 6️⃣ Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          emptyDir: { }
---
# 7️⃣ Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
  type: NodePort
---