---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods","endpoints","services"]
    verbs: ["get", "list","watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["podmonitors"]
    verbs: ["get", "list", "create", "delete","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default  # Adjust this if your Prometheus is in a different namespace
roleRef:
  kind: ClusterRole
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: quarkus-app
  namespace: default
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: quarkus-app  # Label your app's pods accordingly
  podMetricsEndpoints:
    - port: web  # Ensure this matches the port name in your Quarkus app's deployment
      path: /q/metrics  # The path where metrics are exposed
      interval: 5s
      targetPort: 8080
---