---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: quarkus-app
          image: adolfoecs/quarkus-template:latest
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres:5432/quarkusdb"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "quarkus"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "quarkus"
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: "http://keycloak:8080/realms/quarkus-template"
            - name: QUARKUS_OIDC_CLIENT_ID
              value: "quarkus-template-app"
            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              value: "YSFwvyazqPmLukTvwBWa0ZhlhtP3T031"
            - name: QUARKUS_DATASOURCE_JDBC_MAX_SIZE
              value: "100"
            - name: QUARKUS_DATASOURCE_JDBC_ACQUIRE_TIMEOUT
              value: "30S"
            - name: QUARKUS_DATASOURCE_JDBC_CONNECTION_TIMEOUT
              value: "3000"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "5"

---

apiVersion: v1
kind: Service
metadata:
  name: quarkus-app
  labels:
    app: quarkus-app
spec:
  ports:
    - name: web
      port: 8080
  selector:
    app: quarkus-app