name: main build

on:
  push:
    branches:
      - 'main'

jobs:
  run-native-test:
    name: Run all tests including native tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags (otherwise Sonar will report: "Shallow clone detected, no blame information will be provided.")

      - name: Set Up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'

      - name: Enable Docker for Testcontainers
        run: |
          sudo sysctl -w net.ipv4.conf.all.route_localnet=1
          sudo systemctl restart docker

      - name: Allow Testcontainers to Run
        run: echo 'testcontainers.reuse.enable=true' > ~/.testcontainers.properties

      - name: Running checks and native tests
        run: ./gradlew clean testNative