name: build main

on:
  push:
    branches:
      - 'main'

jobs:
  build-jvm:
    name: Run all tests including native tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags (otherwise Sonar will report: "Shallow clone detected, no blame information will be provided.")

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Running checks and native tests
        run: ./gradlew clean testNative -Dquarkus.profile=native-test