name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build-jvm:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags (otherwise Sonar will report: "Shallow clone detected, no blame information will be provided.")

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v3./gradlew
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle.build') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Dependencies check
        run: ./gradlew dependencyUpdates

      - name:  Runs all checks
        run: ./gradlew clean check
